server:
  port: 7500         #当前服务的端口号
  
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurekaserver9000.com:9000/eureka,http://eurekaserver9001.com:9001/eureka
  instance: 
    instance-id: WoniuSpringCloud-config-client # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
spring:
   profiles: dev
   application: 
    name: WoniuSpringCloud-config-client-dev   #当前服务的名字，后面会用到
---

server:
  port: 7500         #当前服务的端口号
  
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurekaserver9000.com:9000/eureka,http://eurekaserver9001.com:9001/eureka
  instance: 
    instance-id: WoniuSpringCloud-config-client # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
spring: 
   profiles: test
   application:
    name: WoniuSpringCloud-config-client-test1   #当前服务的名字，后面会用到
   
